<?php

namespace Database\Seeders;

use App\Models\MsKategoriUsaha;
use Illuminate\Database\Seeder;

class MsKategoriUsahaSeeder extends Seeder
{
    public function run()
    {
        MsKategoriUsaha::insert([[
            'msk_id' => 1,
            'msk_kode' => '01',
            'msk_nama' => 'Menetapkan Tujuan & Visi',
            'msk_status' => true,
            'msk_bobot' => 20,
            'mk_id' => 1,
        ], [
            'msk_id' => 2,
            'msk_kode' => '02',
            'msk_nama' => 'Mengidentifikasi & Memahami Kebutuhan Pemangku Kepentingan',
            'msk_status' => true,
            'msk_bobot' => 20,
            'mk_id' => 1,
        ], [
            'msk_id' => 3,
            'msk_kode' => '03',
            'msk_nama' => 'Memahami Ekosistem, Kemampuan yang Dimiliki & Tantangan Utama',
            'msk_status' => true,
            'msk_bobot' => 20,
            'mk_id' => 1,
        ], [
            'msk_id' => 4,
            'msk_kode' => '04',
            'msk_nama' => 'Mengembangkan Strategi',
            'msk_status' => true,
            'msk_bobot' => 20,
            'mk_id' => 1,
        ], [
            'msk_id' => 5,
            'msk_kode' => '05',
            'msk_nama' => 'Merancang & Menerapkan Sistem Tata Kelola & Manajemen Kinerja',
            'msk_status' => true,
            'msk_bobot' => 20,
            'mk_id' => 1,
        ], [
            'msk_id' => 6,
            'msk_kode' => '01',
            'msk_nama' => 'Mengarahkan Budaya Organisasi dan Memelihara Nilai-Nilai Organisasi',
            'msk_status' => true,
            'msk_bobot' => 25,
            'mk_id' => 2,
        ], [
            'msk_id' => 7,
            'msk_kode' => '02',
            'msk_nama' => 'Menciptakan Kondisi untuk Mewujudkan Perubahan',
            'msk_status' => true,
            'msk_bobot' => 25,
            'mk_id' => 2,
        ], [
            'msk_id' => 8,
            'msk_kode' => '03',
            'msk_nama' => 'Memungkinkan Kreativitas & Inovasi',
            'msk_status' => true,
            'msk_bobot' => 25,
            'mk_id' => 2,
        ], [
            'msk_id' => 9,
            'msk_kode' => '04',
            'msk_nama' => 'Menyatukan Tujuan, Visi, dan Strategi',
            'msk_status' => true,
            'msk_bobot' => 25,
            'mk_id' => 2,
        ], [
            'msk_id' => 10,
            'msk_kode' => '01',
            'msk_nama' => 'Pelanggan: Membangun Hubungan yang Berkelanjutan',
            'msk_status' => true,
            'msk_bobot' => 20,
            'mk_id' => 3,
        ], [
            'msk_id' => 11,
            'msk_kode' => '02',
            'msk_nama' => 'Karyawan: Menarik, Melibatkan, Mengembangkan & Mempertahankan',
            'msk_status' => true,
            'msk_bobot' => 20,
            'mk_id' => 3,
        ], [
            'msk_id' => 12,
            'msk_kode' => '03',
            'msk_nama' => 'Pemangku Kepentingan Bisnis & Pemerintah: Mengamankan & Mempertahankan Dukungan yang Berkelanjutan',
            'msk_status' => true,
            'msk_bobot' => 20,
            'mk_id' => 3,
        ], [
            'msk_id' => 13,
            'msk_kode' => '04',
            'msk_nama' => 'Masyarakat: Berkontribusi pada Pembangunan, Kesejahteraan & Kemakmuran',
            'msk_status' => true,
            'msk_bobot' => 20,
            'mk_id' => 3,
        ], [
            'msk_id' => 14,
            'msk_kode' => '05',
            'msk_nama' => 'Mitra & Pemasok: Membangun Hubungan & Memastikan Dukungan untuk Menciptakan Nilai yang Berkelanjutan',
            'msk_status' => true,
            'msk_bobot' => 20,
            'mk_id' => 3,
        ], [
            'msk_id' => 15,
            'msk_kode' => '01',
            'msk_nama' => 'Merancang Nilai & Bagaimana Nilai itu Diciptakan',
            'msk_status' => true,
            'msk_bobot' => 50,
            'mk_id' => 4,
        ], [
            'msk_id' => 16,
            'msk_kode' => '02',
            'msk_nama' => 'Mengkomunikasikan & Menjual Nilai',
            'msk_status' => true,
            'msk_bobot' => 50,
            'mk_id' => 4,
        ], [
            'msk_id' => 17,
            'msk_kode' => '03',
            'msk_nama' => 'Memberikan Nilai',
            'msk_status' => true,
            'msk_bobot' => 50,
            'mk_id' => 4,
        ], [
            'msk_id' => 18,
            'msk_kode' => '04',
            'msk_nama' => 'Mendefinisikan & Menerapkan Pengalaman Keseluruhan',
            'msk_status' => true,
            'msk_bobot' => 50,
            'mk_id' => 4,
        ], [
            'msk_id' => 19,
            'msk_kode' => '01',
            'msk_nama' => 'Mendorong Kinerja & Mengelola Risiko',
            'msk_status' => true,
            'msk_bobot' => 20,
            'mk_id' => 5,
        ], [
            'msk_id' => 20,
            'msk_kode' => '02',
            'msk_nama' => 'Mentransformasi Organisasi untuk Masa Depan',
            'msk_status' => true,
            'msk_bobot' => 20,
            'mk_id' => 5,
        ], [
            'msk_id' => 21,
            'msk_kode' => '03',
            'msk_nama' => 'Mendorong Inovasi & Memanfaatkan Teknologi',
            'msk_status' => true,
            'msk_bobot' => 20,
            'mk_id' => 5,
        ], [
            'msk_id' => 22,
            'msk_kode' => '04',
            'msk_nama' => 'Memanfaatkan Data, Informasi & Pengetahuan',
            'msk_status' => true,
            'msk_bobot' => 20,
            'mk_id' => 5,
        ], [
            'msk_id' => 23,
            'msk_kode' => '05',
            'msk_nama' => 'Mengelola Aset & Sumber Daya',
            'msk_status' => true,
            'msk_bobot' => 20,
            'mk_id' => 5,
        ], [
            'msk_id' => 24,
            'msk_kode' => '01',
            'msk_nama' => 'Hasil Persepsi Pelanggan',
            'msk_status' => true,
            'msk_bobot' => 40,
            'mk_id' => 6,
        ], [
            'msk_id' => 25,
            'msk_kode' => '02',
            'msk_nama' => 'Hasil Persepsi Masyarakat',
            'msk_status' => true,
            'msk_bobot' => 40,
            'mk_id' => 6,
        ], [
            'msk_id' => 26,
            'msk_kode' => '03',
            'msk_nama' => 'Hasil Persepsi Pemangku Kepentingan Bisnis & Pemerintah',
            'msk_status' => true,
            'msk_bobot' => 40,
            'mk_id' => 6,
        ], [
            'msk_id' => 27,
            'msk_kode' => '04',
            'msk_nama' => 'Hasil Persepsi Masyarakat',
            'msk_status' => true,
            'msk_bobot' => 40,
            'mk_id' => 6,
        ], [
            'msk_id' => 28,
            'msk_kode' => '05',
            'msk_nama' => 'Hasil Persepsi Mitra & Pemasok',
            'msk_status' => true,
            'msk_bobot' => 40,
            'mk_id' => 6,
        ], [
            'msk_id' => 29,
            'msk_kode' => '01',
            'msk_nama' => 'Pencapaian Tujuan Strategis',
            'msk_status' => true,
            'msk_bobot' => 50,
            'mk_id' => 7,
        ], [
            'msk_id' => 30,
            'msk_kode' => '02',
            'msk_nama' => 'Pencapaian dalam Mendorong Kinerja',
            'msk_status' => true,
            'msk_bobot' => 50,
            'mk_id' => 7,
        ], [
            'msk_id' => 31,
            'msk_kode' => '03',
            'msk_nama' => 'Pencapaian dalam Mendorong Transformasi',
            'msk_status' => true,
            'msk_bobot' => 50,
            'mk_id' => 7,
        ], [
            'msk_id' => 32,
            'msk_kode' => '04',
            'msk_nama' => 'Langkah-langkah prediksi untuk Masa Depan',
            'msk_status' => true,
            'msk_bobot' => 50,
            'mk_id' => 7,
        ],]);
    }
}
